### ISSUE TITLE
NONE下，启动cloud，连接不上nacos

### ISSUE THREAD

**Issue by xswby** [zuihou/lamp-cloud#104]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：2.0.2

# 问题描述：
启动gateway模块或者file模块，暂时只尝试这二个，发现连不上nacos
模式用：NONE
nacos用单例模式，telnet测试8848，9848都是通的
# 报错截图
[ERROR] [82077] [] [main:25590] [c.a.nacos.common.remote.client.grpc.GrpcClient.printIfErrorEnabled:99] Server check fail, please check server 我的服务器ip ,port 9848 is available , error ={}

java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 3 milliseconds, 25939 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@4784013e[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@4c98a6d5, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@392a04e7, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@7f02251}}}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
关闭防火墙，或者 开启端口

注意：切记部署nacos 2.x的服务器，需要使其防火墙开通8848、9848、9849三个端口

https://www.kancloud.cn/zuihou/zuihou-admin-cloud/1284756
