### ISSUE TITLE
lamp-cloud依赖maven库缺失

### ISSUE THREAD

**Issue by 925178365** [zuihou/lamp-cloud#114]
后端使用的是lamp-cloud
JDK 版本 : 8
源码版本：3.0.1
MySQL：8
Nacos：2.0.3

问题描述：
maven依赖问题
Cannot resolve com.tangyh.lamp:sdk-server:1.2.2
多次下载 clean install都无法下载
其他依赖正常 仅这一个依赖无效
![1635762867(1)](https://user-images.githubusercontent.com/37007782/139658933-a0a288b2-27e0-4675-b390-26513e5dd36e.jpg)

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
请下载正版 项目源码， 本项目重来没有过你截图的内容
