### ISSUE TITLE
开源版Lamp-cloud，在COLUMN模式下成功启动后端，Lamp-web开发环境启动后，输入用户名密码提示【 请填写正确的客户端ID或者客户端秘钥】

### ISSUE THREAD

**Issue by MisakaRei** [zuihou/lamp-cloud#124]
# 版本信息：
JDK 版本(必填) : 11
源码版本(必填)：3.6.0
MySQL(必填)： 8.0.28
Nacos(必填)：2.0.3

# 问题描述：
开源版Lamp-cloud，【初次】在COLUMN模式下成功启动后端，Lamp-web开发环境启动后，输入用户名密码提示【 请填写正确的客户端ID或者客户端秘钥】，无法登入系统。

# 报错截图
后端成功启动
![image](https://user-images.githubusercontent.com/57378623/152111866-debdf286-2794-4502-bd18-8a3bdb211957.png)
Nacos服务列表
![image](https://user-images.githubusercontent.com/57378623/152111901-c7ec84aa-9b5e-47db-9b50-a99c7face7e1.png)
前端成功启动
![image](https://user-images.githubusercontent.com/57378623/152111990-3b8b7854-f062-4a47-9731-24949b08ee07.png)
系统无法登入，提示【请填写正确的客户端ID或者客户端秘钥】
![image](https://user-images.githubusercontent.com/57378623/152111468-cec6ff1c-f0b2-4e3d-9f49-3f49e4458764.png)
后端OauthServerApplication控制台
![image](https://user-images.githubusercontent.com/57378623/152112856-eea2ed4f-e445-44af-9cc1-258d04fa0543.png)

# 重现步骤
1. 部署后台、前端
2. 打开前端页面，并输入正确租户编号、用户名、密码
3. 页面提示【 请填写正确的客户端ID或者客户端秘钥】，无法登入系统

BTW:
在上述情况中，Nacos中mysql.yml使用的是lamp_defaults数据库，离线文档中COLUMN模式向 lamp_column 库中导入 各种表数据，我在启动项目时，发现了这个问题，后向lamp_defaults数据库重新执行了相关sql文件，不知是我在配置过程中有误导致了这个情形的产生，还是离线文档中有所纰漏导致了这个情况呢。

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
重新导入c_application表的数据

![image](https://user-images.githubusercontent.com/8500410/152115309-b55ea3f2-1f7e-423d-9f51-b8cc2f405ae9.png)


并确保 `tenant_code` 字段的值正确
