### ISSUE TITLE
lamp-cloud项目，在部署后，测试功能时，多出弹出权限提醒

### ISSUE THREAD

**Issue by MisakaRei** [zuihou/lamp-cloud#126]
# 版本信息：
JDK 版本(必填) : 11
源码版本(必填)：3.6.0
MySQL(必填)： 8.0.28
Nacos(必填)：2.0.3

# 问题描述：
登入超级管理员帐号（lamp/lamp）：
1、进入系统设置—》在线用户页面，页面弹出错误提醒，执行方法[list]需要[hasAnyPermission('authority:online:view')]权限，鉴权出错，随后自动跳转到登录页面
2、进入系统设置—》角色管理页面，页面弹出错误提醒，执行方法[list]需要[hasAnyPermission('authority:online:view')]权限，鉴权出错，随后自动跳转到登录页面
3、在进入其他菜单，再进入角色管理页面时，不弹出错误提醒，但是点击角色后操作的按钮时，页面弹出错误提醒，执行方法[findResourceListByRoleId]需要[hasAnyPermission('authority:role:view')]权限，随后自动跳转到登录页面

# 报错截图
![image](https://user-images.githubusercontent.com/57378623/152371965-39b213cd-3e69-4015-8ae1-b26116504b06.png)
![image](https://user-images.githubusercontent.com/57378623/152372812-e14d30e8-cf1d-4e0e-8ce0-ee8c2fcf9555.png)
![image](https://user-images.githubusercontent.com/57378623/152373444-ad861472-be5a-4090-a12b-965ebdfb1345.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
请先了解本项目的URI权限如何配置和授权。

或直接修改common.yml中全局配置，禁用全局uri权限
