### ISSUE TITLE
使用jenkins 从传输单个jar包过慢

### ISSUE THREAD

**Issue by wuhao2721** [zuihou/lamp-cloud#127]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：
203

# 问题描述：

SSH: Connecting from host [iZwz99xeomvq1omj9cu7tuZ]
SSH: Connecting with configuration [120.78.11.123_dev] ...
SSH: EXEC: completed after 201 ms
SSH: Disconnecting configuration [120.78.11.123_dev] ...
ERROR: Exception when publishing, exception message [Exec exit status not zero. Status [2]]

传输一个jar包140M传20分钟并报以上错误

# 报错截图

![企业微信截图_16456015177176](https://user-images.githubusercontent.com/39933874/155277350-4c3954f2-c7c0-4875-b061-c6bc60e542e7.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
1. jenkins 和 部署服务器保证内网传输可加快速度。

**Comment by wuhao2721** [comment]
我试一下

**Comment by zuihou** [comment]
在传输jar过程中，可以在部署服务器通过 `ls ` 等命令查看jar体积是否在不断的变大， 在不停的变大，说明传输没问题，只是网络带宽的问题。

**Comment by wuhao2721** [comment]
ERROR: Exception when publishing, exception message [Exec exit status not zero. Status [2]]
还是报这个错不过内网传输几秒就传输过来了

**Comment by wuhao2721** [comment]
> 在传输jar过程中，可以在部署服务器通过 `ls ` 等命令查看jar体积是否在不断的变大， 在不停的变大，说明传输没问题，只是网络带宽的问题。

报下面的错

**Comment by zuihou** [comment]
1. 传递一样的参数给 server_run.sh  ， 并手动执行server_run.sh 脚本。
2. 确保手动执行脚本能正常启动，就网上搜索jenkins执行脚本不成功，但手动执行脚本成功的原因。
