### ISSUE TITLE
服务使用jenkins没起来，我选的不对吗

### ISSUE THREAD

**Issue by wuhao2721** [zuihou/lamp-cloud#128]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：
203

# 问题描述：
![企业微信截图_16456029367279](https://user-images.githubusercontent.com/39933874/155279985-d60d3b65-f3f7-4348-bf9f-5eceeebd482d.png)
![企业微信截图_16456029731396](https://user-images.githubusercontent.com/39933874/155280040-3d18be72-0c2b-4fd0-82ed-f073e4533d1a.png)
![企业微信截图_1645603006675](https://user-images.githubusercontent.com/39933874/155280101-e4110714-7513-4cf5-b972-42b2c4413ba0.png)

服务没起来，还是我看的不对

# 报错截图

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
只要能执行脚本，配置就没问题，建议多使用搜索引擎，如：

https://blog.csdn.net/u012725714/article/details/100160238
