### ISSUE TITLE
jenkinsfile 文件运行有误

### ISSUE THREAD

**Issue by wuhao2721** [zuihou/lamp-cloud#129]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：
203

# 问题描述：
感觉脚本顺序有问题，脚本可执行，这行命令感觉没执行 jar控制台没输出
bash 
# 报错截图
![企业微信截图_16456073006425](https://user-images.githubusercontent.com/39933874/155289303-127d3b25-a3ff-4579-9ae1-cdbfa669fed9.png)
![企业微信截图_1645607359372](https://user-images.githubusercontent.com/39933874/155289437-6fb6d6bd-445b-4b4c-8141-3af8a0030ca7.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by wuhao2721** [comment]
+ nohup java -javaagent:/data_prod/agent/skywalking-agent.jar -Dskywalking.agent.service_name=lamp-oauth-server -jar -server -Xms256M -Xmx256M -Xss512k -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=512M -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data_dev/logs/heap_dump_lamp-oauth-server.hprof -Dspring.profiles.active=dev /data_dev/target/lamp-oauth-server.jar lamp-oauth-server

**Comment by zuihou** [comment]
执行了的， jenkins执行脚本本来就有的问题：
1. 看不到脚本输出的日志
2. 有可能会导致脚本执行不成功（不同的jenkins版本和服务器安装环境表现不同，可以在网上自行找解决方案）
