### ISSUE TITLE
如何查看jenkins执行脚本并控制台打印执行信息

### ISSUE THREAD

**Issue by wuhao2721** [zuihou/lamp-cloud#133]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：203

# 问题描述：
server_run.sh脚本中执行执行jar包没启动，控制台如何打印执行脚本信息并起来

# 报错截图
![企业微信截图_16456796257204](https://user-images.githubusercontent.com/39933874/155462183-e99cce9c-924d-4f7c-a924-3abd23dd784d.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
看不到，找到如何查看的方法可以告诉我
