### ISSUE TITLE
新建租户，初始化的时候，新租户的菜单未初始化resourceType的值，导致新租户登录菜单不存在

### ISSUE THREAD

**Issue by miki-hmt** [zuihou/lamp-cloud#134]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：lamp-cloud,lamp-cloud-plus
MySQL(必填)： 5.7.9
Nacos(必填)：203

# 问题描述：
column模式初始化新租户的时候，菜单未设置resourceType的值，导致新租户登录的时候，菜单列表为空

# 报错截图
![image](https://user-images.githubusercontent.com/45377370/156332833-148a9f7a-8867-49bb-8c4c-58ca4d050ca4.png)

![image](https://user-images.githubusercontent.com/45377370/156333297-4b5ca55b-03e2-4a9d-b810-5d2f1c670294.png)

查询的时候反而做了筛选条件
![image](https://user-images.githubusercontent.com/45377370/156332951-5bc513a4-8472-449d-938b-0e01c0744fb4.png)

# 重现步骤
1. 访问了什么接口？
/menu/router
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？
新租户的菜单显示为空

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
已修复
