### ISSUE TITLE
Feign调用传递header参数问题

### ISSUE THREAD

**Issue by tomcat555** [zuihou/lamp-cloud#137]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
FeignAddHeaderRequestInterceptor拦截器不应该传递前端request中的content-length字段，会导致api请求失败

# 报错截图

# 重现步骤
1. 访问了什么接口？
通过feign在一个接口中调用两次其他服务的api接口，第二次会报400 Bad Request
3. 传递什么参数？
4. 后端控制台报了什么错？
5. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
最新代码已经改了！
