### ISSUE TITLE
按部署文件配置出错到nginx时,lamp-clound部署文档.pdf

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#139]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.x
MySQL(必填)： 5.7.
Nacos(必填)：2.1.0

# 问题描述：
按部署文件配置出错到nginx时,lamp-clound部署文档.pdf
[root@localhost html]# docker run -d --name nginx --restart=always -p 80:80 -v /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf -v /data/docker/webapp/:/data/html/webapp/ -v /data/docker/fastdfs/:/home/fastdfs nginx
a1a6e93ebaa5bf3cf8bdfa4a3469a241e71d156552ce4c4af34e443cf85e8c13
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/docker/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
# 报错截图
![image](https://user-images.githubusercontent.com/17776370/169928856-1d80738c-4bc1-44ad-a1bc-050a97128b61.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by victoirechan** [comment]
![image](https://user-images.githubusercontent.com/17776370/169929029-67f02a42-8cfe-4536-87d3-146ea6312f58.png)

**Comment by zuihou** [comment]
1. 报错日志应该用 markdown 语法  \```  代码片段包裹  ``` 如：
```
[root@localhost html]# docker run -d --name nginx --restart=always -p 80:80 -v /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf -v /data/docker/webapp/:/data/html/webapp/ -v /data/docker/fastdfs/:/home/fastdfs nginx
a1a6e93ebaa5bf3cf8bdfa4a3469a241e71d156552ce4c4af34e443cf85e8c13
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/docker/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

2. 错误日志：  `error during container init: error mounting "/data/docker/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.` 中文意思：

容器初始化期间出错：将“/data/docker/nginx/nginx.conf”装载到根目录/etc/nginx/nginx.conf”时出错：挂载 /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf（via/proc/self/fd/6），标志：0x5000：不是目录：未知：
您是否正在尝试将目录装载到文件上（反之亦然）？检查指定的主机路径是否存在，是否为预期类型。

说明在你宿主机上 /data/docker/nginx/nginx.conf 是一个目录，它应该是一个文件！

**Comment by victoirechan** [comment]
问题解决了，去掉目录，复制配置文件进去
