### ISSUE TITLE
Error:(60, 52) java: -source 1.5 中不支持方法引用   (请使用 -source 8 或更高版本以启用方法引用)

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#140]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6.0
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
编译lamp-cloud-pro-column-master项目时出错，Error:(60, 52) java: -source 1.5 中不支持方法引用
  (请使用 -source 8 或更高版本以启用方法引用)

# 报错截图

![image](https://user-images.githubusercontent.com/17776370/169962760-c4b7faeb-d54f-4c29-8d47-b536501f1e0f.png)

重新设置了1.8版本，出现同样错误
![image](https://user-images.githubusercontent.com/17776370/169970724-80587bc7-1d9c-4c50-952d-ecca06f76d1b.png)

![image](https://user-images.githubusercontent.com/17776370/169970926-820b7d44-8389-45b6-a3b1-28c7812b1a63.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
1. IDEA 的识别问题，自行搜索解决，所有有jdk的地方都设置成 java 8.
2. IDEA 升级最新版， 你这版本太低了。
