### ISSUE TITLE
Error:(3, 29) java: 程序包top.tangyh.basic.base不存在

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#141]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6.0
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
编译lamp-cloud-pro-column-master时出错
Error:(3, 29) java: 程序包top.tangyh.basic.base不存在

# 报错截图
![image](https://user-images.githubusercontent.com/17776370/169985581-e83ac3e7-0c11-406b-93c6-757a2c42fc78.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
仓库面找 lamp-util-pro ，并进行编译。

建议先阅读 gitlab中 4.x 文档。
