### ISSUE TITLE
lamp-cloud-pro-column源码编译后，未找到相应JAR包

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#142]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
lamp-cloud-pro-column源码编译后，只有3和4有，其他没有
1 docker build ‐‐build‐arg JAR_FILE=lamp‐authority‐server.jar ‐t lamp‐autho
rity‐server:v1 .
2 docker build ‐‐build‐arg JAR_FILE=lamp‐file‐server.jar ‐t lamp‐file‐serve
r:v1 .
3 docker build ‐‐build‐arg JAR_FILE=lamp‐oauth‐server.jar ‐t lamp‐oauth‐ser
ver:v1 .
4 docker build ‐‐build‐arg JAR_FILE=lamp‐gateway‐server.jar ‐t lamp‐
gateway‐server:v1 .
5 docker build ‐‐build‐arg JAR_FILE=lamp‐msg‐server.jar ‐t lamp‐msg‐
server:v1 .

# 报错截图

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by victoirechan** [comment]
![image](https://user-images.githubusercontent.com/17776370/170910797-2f883e14-0b6f-49f4-9421-7374e40158e9.png)
执行错误，docker build ‐‐build‐arg JAR_FILE=lamp‐oauth‐server.jar ‐t lamp‐oauth‐server:v1 .

**Comment by zuihou** [comment]
mvn编译项目后，jar存放在lamp-xxx-server下，不在根目录

**Comment by zuihou** [comment]
![image](https://user-images.githubusercontent.com/8500410/171112147-4d8f497b-10a5-4d76-90a6-0788380e460e.png)

**Comment by victoirechan** [comment]
执行错误，docker build ‐‐build‐arg JAR_FILE=lamp‐oauth‐server.jar ‐t lamp‐oauth‐server:v1 .
![image](https://user-images.githubusercontent.com/17776370/171116502-f042cb1e-fa74-46d5-9c70-9005464232b4.png)
