### ISSUE TITLE
lamp-clound部署文档，创建网络错误

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#143]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
创建网桥网络错误，8 docker network create ‐‐subnet=173.17.0.2/24 custom(网桥名称，随便写即可) ‐
‐‐‐创建网桥

# 报错截图
![image](https://user-images.githubusercontent.com/17776370/170935814-189d3d57-7462-43da-bbcb-2169c89a0356.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
docker基础知识，自行解决
