### ISSUE TITLE
Error running OauthServerApplication. Command line is too long.

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#144]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6.1
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
编译运行OauthServerApplication出错
# 报错截图
![image](https://user-images.githubusercontent.com/17776370/171085015-02a16e04-540d-4b6d-b657-1e0c0e0986f8.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by victoirechan** [comment]
# 启动项目

1. 先确保`nacos`、`MySQL`、`Redis`、 `RabbitMQ`(可选)、等基础服务是否启动成功
2. 逐一启动 OauthServerApplication、SystemServerApplication、BaseServerApplication、GatewayServerApplication、MonitorApplication

**Comment by victoirechan** [comment]
![image](https://user-images.githubusercontent.com/17776370/171085715-dff112e2-ce28-49bc-9c2e-8429cbb59d7a.png)
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'systemApiScanController' defined in file [E:\Victoire.Resource.FRF\LampSourceCode\lamp-util-pro\lamp-scan-starter\target\classes\top\tangyh\basic\scan\controller\SystemApiScanController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getRequestMappingScanUtils' defined in class path resource [top/tangyh/basic/scan/ScanAutoConfigure.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [top.tangyh.basic.scan.utils.RequestMappingScanUtils]: Factory method 'getRequestMappingScanUtils' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)

**Comment by victoirechan** [comment]
![image](https://user-images.githubusercontent.com/17776370/171085782-93098153-b16c-4200-ae9e-bdf5ed68ec6a.png)
添加图中文字后，再运行，又出错

**Comment by victoirechan** [comment]
![image](https://user-images.githubusercontent.com/17776370/171086384-dcd9f49c-34f7-4a61-8902-4b0f6bda69cd.png)

**Comment by zuihou** [comment]
idea启动项改一下配置，有个jarfile  classpath等等之类的配置，改一下。在外面没法截图

**Comment by zuihou** [comment]
![image](https://user-images.githubusercontent.com/8500410/171111380-46715daa-aeb1-499f-9ea2-ce38e516edb1.png)
