### ISSUE TITLE
启动项目lamp-cloud-pro-column出错

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#145]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6.1
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
# 启动项目

1. 先确保`nacos`、`MySQL`、`Redis`、 `RabbitMQ`(可选)、等基础服务是否启动成功
2. 逐一启动 OauthServerApplication、SystemServerApplication、BaseServerApplication、GatewayServerApplication、MonitorApplication

# 报错截图
![image](https://user-images.githubusercontent.com/17776370/171104133-c31ada40-8fda-4740-b09b-f233f374ff8f.png)

启动 OauthServerApplication、SystemServerApplication

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'systemApiScanController' defined in file [E:\Victoire.Resource.FRF\LampSourceCode\lamp-util-pro\lamp-scan-starter\target\classes\top\tangyh\basic\scan\controller\SystemApiScanController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getRequestMappingScanUtils' defined in class path resource [top/tangyh/basic/scan/ScanAutoConfigure.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [top.tangyh.basic.scan.utils.RequestMappingScanUtils]: Factory method 'getRequestMappingScanUtils' threw exception; nested exception is java.lang.NullPointerException

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
检查common.yml 配置，里面少了:

```
spring:
  mvc:
    pathmatch:
      # 升级springboot2.6.6后临时处理，防止swagger报错
      matching-strategy: ANT_PATH_MATCHER
```

**Comment by ttitfly** [comment]
还有种情况是防火墙导致，需要关闭防火墙（注意是关闭，不是防火墙开启端口）
