### ISSUE TITLE
在本地启动lamp-base、lamp-system、lamp-oauth、lamp-generator、lamp-gateway和lamp-web-pro

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#151]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6.1
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
本地启动服务，出错：
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[lamp-base-server:18764::] 2022-06-10 10:08:35.962:[ERROR] [8156] [] [main:19650] [o.s.b.diagnostics.LoggingFailureAnalysisReporter.report:40] 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles dev are currently active).

[lamp-base-server:18764::] 2022-06-10 10:08:35.965:[ WARN] [8156] [] [Thread-17:19653] [com.alibaba.nacos.common.http.HttpClientBeanHolder.shutdown:108] [HttpClientBeanHolder] Start destroying common HttpClient
[lamp-base-server:18764::] 2022-06-10 10:08:35.965:[ WARN] [8156] [] [Thread-35:19653] [com.alibaba.nacos.common.notify.NotifyCenter.shutdown:136] [NotifyCenter] Start destroying Publisher

Process finished with exit code 1

# 报错截图
![image](https://user-images.githubusercontent.com/17776370/172976248-b969fb98-aca5-4f96-9d02-53a6ae0c3f15.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
https://github.com/zuihou/lamp-cloud/discussions/49
