### ISSUE TITLE
单独建立项目，如何获取            <version>${lamp-project.version}</version>

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#152]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6.1
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
单独建立项目，如何获取            <version>${lamp-project.version}</version>

# 报错截图
![image](https://user-images.githubusercontent.com/17776370/172998182-6dbca496-9d5d-409a-9b26-f1e7ba4f0f03.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
觉得有必要购买一个培训服务， java、maven、spring基础知识需要先掌握

**Comment by zuihou** [comment]
参考 lamp-base/pom.xml  、lamp-base-api/pom.xml  的配置， 重点看 <parent> 节点
