### ISSUE TITLE
为lamp-cloud或lamp-boot项目新建新服务

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#153]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6.1
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
为lamp-cloud或lamp-boot项目新建新服务，提示网络资源无法获取。
我是通过服务端运行的后台管理系统进入项目生成

# 报错截图
![image](https://user-images.githubusercontent.com/17776370/172998527-0edc4a8f-8d83-4a2a-911c-51c90e2b8f52.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
1. 看代码生成器服务后台日志， 没日志不知道原因
2. 看 “注意事项“”
