### ISSUE TITLE
编译运行oauthserverapplication 出错

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#154]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6.1
MySQL(必填)： 5.7.9
Nacos(必填)：2.0.3

# 问题描述：
编译运行oauthserverapplication 出错

# 报错截图
![image](https://user-images.githubusercontent.com/17776370/173169032-6709feca-f203-4134-9860-3888096f9210.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by victoirechan** [comment]
Error creating bean with name 'getRequestMappingScanUtils' defined in class path resource [top/tangyh/basic/scan/ScanAutoConfigure.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [top.tangyh.basic.scan.utils.RequestMappingScanUtils]: Factory method 'getRequestMappingScanUtils' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)

**Comment by zuihou** [comment]
![image](https://user-images.githubusercontent.com/8500410/173310568-c63d0791-05b8-46bb-a5bd-e94c1d82d577.png)

1. 检查 common.yml 中这段配置一致，并且程序启动时，能正常读取到这个配置文件。
2. 如何确保读取到正确的配置了？  debugger 代码，然后 env.getProperty("xxxxxx");

![image](https://user-images.githubusercontent.com/8500410/173310530-8c3c4003-a9cb-4fe3-b1d9-02caab2b7ff9.png)

**Comment by zuihou** [comment]
https://github.com/dromara/lamp-cloud/issues/145
