### ISSUE TITLE
lamp-parent 这个依赖 在哪里 maven引入报错

### ISSUE THREAD

**Issue by SUNFei1126** [zuihou/lamp-cloud#156]
<parent>
        <groupId>top.tangyh.basic</groupId>
        <artifactId>lamp-parent</artifactId>
        <version>3.7.0</version>
        <relativePath/>
    </parent>
maven 依赖引入时 报错找不到

**Comment by zuihou** [comment]
下载，并编译 lamp-util 项目。

按照文档步骤来： https://www.kancloud.cn/zuihou/zuihou-admin-cloud/2405108
