### ISSUE TITLE
当 租户模式为“ SCHEMA” 时,是否支持 租户数据库配置是REMOTE模式

### ISSUE THREAD

**Issue by zeyouwang** [zuihou/lamp-cloud#158]
# 版本信息：
后端使用的是lamp-cloud
JDK 版本(必填) : 1.8.0
源码版本(必填)：3.0.2-SNAPSHOT
MySQL(必填)： 5.7.9
Nacos(必填)：1.3.0

# 问题描述：
当  租户模式为“ SCHEMA” 时，创建租户时， 链接模式 为 REMOTE模式，这个功能 是 好的吗？租户数据库配置是REMOTE模式
对应的业务 都能用吗？ 我在您的测试环境体验不出来，求解答

**Comment by zuihou** [comment]
只有datasource模式支持

**Comment by zuihou** [comment]
其他模式只有用local
