### ISSUE TITLE
lamp-cloud升级4.9.0，编译出错

### ISSUE THREAD

**Issue by victoirechan** [zuihou/lamp-cloud#165]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
lamp-cloud升级4.9.0，编译出错

# 报错截图
![image](https://user-images.githubusercontent.com/17776370/182277968-93d1fce1-d86b-4894-a0e3-abe09bf0c9cf.png)
![image](https://user-images.githubusercontent.com/17776370/182277997-1b652228-dfe9-4c90-bc0d-3365e4f6d658.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
更新代码

**Comment by victoirechan** [comment]
代码已经更新过的
