### ISSUE TITLE
RestTemplateHeaderInterceptor中header设置顺序

### ISSUE THREAD

**Issue by xiaoyu-spark** [zuihou/lamp-cloud#167]
RestTemplateHeaderInterceptor中，使用contextUtil的值覆盖header中的值会不会更换一些，使用过程中，contextUtil和header的key会重复，且会在代码中修改

**Comment by xiaoyu-spark** [comment]
![图片](https://user-images.githubusercontent.com/18681855/183795549-dd82edc0-2bb4-44bc-8a60-27af20d833a0.png)
这样改会影响其他滴定法吗

**Comment by zuihou** [comment]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/8500410/183799139-279a9e2f-67ee-4db1-8238-3679d7d43409.png">

**Comment by zuihou** [comment]
DB 操作时，只能从 ContextUtil 中取租户ID/租户编码 数据来控制切换，不能取请求头中的 租户ID/租户编码 ， 因为定时、异步等场景没有请求头！
