### ISSUE TITLE
RestTemplateHeaderInterceptor异步线程中的问题

### ISSUE THREAD

**Issue by xiaoyu-spark** [zuihou/lamp-cloud#168]
该类在调用中给其下游服务传递值，但是        RequestAttributes requestAttributes = RequestContextHolder.getRequestAttributes();
在异步调用中存在问题，此时请求结束，request销毁，上游服务的值无法传递给下游服务器

**Comment by zuihou** [comment]
异步线程 需要手动调用ContextUtil 设置参数，方可传递下去
