### ISSUE TITLE
项目生成时freemarker文件中未引入LogApi

### ISSUE THREAD

**Issue by pinkcao** [zuihou/lamp-cloud#179]
# 版本信息：
JDK 版本(必填) : 11
源码版本(必填)：4.11.0 lamp-cloud-pro-datasource-column
MySQL(必填)： 8.0.29
Nacos(必填)：2.0.2

# 问题描述：
使用lamp-generator新建一个服务时报错，提示找不到LogApi

应该是在自动生成模板中少import了LogApi

需要在Testservice3WebConfiguration.java中
import top.tangyh.lamp.common.api.LogApi

# 报错截图
![bugInfo3](https://user-images.githubusercontent.com/36530450/187840310-d881f967-c8cc-49e1-b8dd-a42ca29b9007.PNG)

# 重现步骤
1.在项目生成中生成一个新项目
2.nacos配置gateway，新起一个对应的yml文件
3.运行项目

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
dev 分支已修复
