### ISSUE TITLE
运行新建服务无法注入appendixController

### ISSUE THREAD

**Issue by pinkcao** [zuihou/lamp-cloud#180]
# 版本信息：
JDK 版本(必填) : 11
源码版本(必填)：4.11.0 lamp-cloud-pro-datasource-column
MySQL(必填)： 8.0.29
Nacos(必填)：2.0.2

# 问题描述：
新建服务后运行服务，有bean注入失败
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appendixController' defined in file [E:\Projects\BackEnd\lamp-cloud\lamp-public\lamp-file-sdk\target\classes\top\tangyh\lamp\file\controller\AppendixController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baseAppendixServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'top.tangyh.lamp.file.mapper.AppendixMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

# 报错截图
![bugInfo4](https://user-images.githubusercontent.com/36530450/187841103-a770aff8-842e-4cd5-a7bb-7b364223e6a5.PNG)

# 重现步骤
1.新建一个服务
2.将LogApi引入至WebConfiguration
3.配置nacos
4.运行服务

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
搜索看下 @MapperScan(basePackages = {BUSINESS_PACKAGE, UTIL_PACKAGE}, annotationClass = Repository.class) 

是否包含你的新建的服务的包名

**Comment by pinkcao** [comment]
> 

1.新建一个服务后搜索@MapperScan(basePackages = {BUSINESS_PACKAGE, UTIL_PACKAGE}, annotationClass = Repository.class)
显示一共两处出现，如图

![bugInfo5](https://user-images.githubusercontent.com/36530450/187849974-02865e46-2c4f-4e30-88a0-137532ea64a0.PNG)
一处是ftl文件，一处是lamp-public下的

**Comment by zuihou** [comment]
改 lamp-public

**Comment by zuihou** [comment]
ftl 是生成代码的模板

**Comment by pinkcao** [comment]
> 
![bugInfo6](https://user-images.githubusercontent.com/36530450/187853500-3d65c5da-f4f6-4fb3-b1f8-26dd93570e11.PNG)

上图是我生成所输入的项，其中包名就是top.tangyh.lamp，与BizConstant中的BUSINESS_PACKAGE相一致,对应到basePackages中的BUSINESS_PACKAGE

![bugInfo7](https://user-images.githubusercontent.com/36530450/187853695-f91a5d90-bf58-4d21-bd2d-5fda23866339.PNG)


![bugInfo8](https://user-images.githubusercontent.com/36530450/187853709-26554ddc-606b-4c89-939f-3443dcb29c36.PNG)

因此我有点不知道怎么修改lamp-public，可否说的再详细一些

**Comment by zuihou** [comment]
![image](https://user-images.githubusercontent.com/8500410/187861125-c3af2650-9266-4458-b124-66186f89f85d.png)

**Comment by pinkcao** [comment]
ok
