### ISSUE TITLE
日志打印的租户号是“9999”，但是 实际数据库执行的 库 不是  “9999” 的库

### ISSUE THREAD

**Issue by zeyouwang** [zuihou/lamp-cloud#184]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：1.3.0

# 问题描述：
 日志打印的租户号是“9999”，但是 实际数据库执行的 库 不是  “9999” 的库，请问是什么原因 上下文乱了吗？

# 报错截图
![image](https://user-images.githubusercontent.com/30871194/188622558-21fa60c0-36ce-4afd-bedc-f3d7e8c4646d.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
注意理解： ContextUtil.getTenantId()  和 ContextUtil.getBasePoolNameHeader() 的区别
getTenantId 是指当前请求属于那个租户，   
getBasePoolNameHeader 是指当前请求查询那个租户。

日志前面的9999，是打印的 getTenantId； 后面的43529 取的是 getBasePoolNameHeader 。

**Comment by zeyouwang** [comment]
> 在看看你业务代码里调用 ContextUtil.setTenant 没

明白了，谢谢 汤哥，确实 是 调用了 调用 ContextUtil.setTenant
