### ISSUE TITLE
项目部署到服务器验证码没显示

### ISSUE THREAD

**Issue by leezhang19** [zuihou/lamp-cloud#185]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：lamp-web 3.7.0 lamp-boot：3.7.0
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：项目部署到服务器验证码没显示
![image](https://user-images.githubusercontent.com/57745942/189331896-4e82eb5f-480c-4a4d-8920-501e95fa4f7b.png)

# 报错截图

# 重现步骤
1. 访问了什么接口？/api/oauth/anno/captcha
2. 传递什么参数？captcha?key=98627017F09465CC1344553C1662719063199&ts=166271906322
3. 后端控制台报了什么错？
![image](https://user-images.githubusercontent.com/57745942/189331013-bd870946-8e0f-46fe-9813-2123e3fe5cac.png)

5. 前端控制台报了什么错？
![image](https://user-images.githubusercontent.com/57745942/189331087-eea35709-70d7-4053-aca5-1f71fa8e3ef9.png)

访问http://ip:8760/anno/captcha?key=123验证码能出来

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
lamp-web 和 lamp-gateway-server 都需要nginx 代理，然后浏览器访问 lamp-web 以及 lamp-web中请求的接口均需要是nginx代理的ip+port

**Comment by zuihou** [comment]
后端是lamp-boot，nginx代理配置跟lamp-cloud不一样，有区别！
