### ISSUE TITLE
org.apache.ibatis.binding.BindingException: Invalid bound Statement (not found): top.tangyh.lamp.tenant.mapper.InitDatabaseMapper.selectTenantCodeList

### ISSUE THREAD

**Issue by pinkcao** [zuihou/lamp-cloud#186]
# 版本信息：
JDK 版本(必填) : JDK11
源码版本(必填)：4.11.0 lamp-cloud-pro-datasource-column
MySQL(必填)： 8.0.29
Nacos(必填)：2.0.2

# 问题描述：
想要简化工程目录，使得通过每个generator生成出来的微服务可被直接运行

因此对于使用generator生成的微服务进行了一些改造，使其做到应该能正常跑起来。

但目前改造完后将报错org.apache.ibatis.binding.BindingException: Invalid bound Statement (not found): top.tangyh.lamp.tenant.mapper.InitDatabaseMapper.selectTenantCodeList
推断是@MapperScan未扫到包，但该方法类路径确实是top.tangyh.lamp下的，应该会被扫到，因此有点不知道该如何处理

经过测试发现，当工程项目将lamp-public引入后，服务可正常运行，但我想实现的是maven工程中也不同时引入lamp-public，只将lamp-public install至本地即可。

我想要知道哪里的配置项需要修改以使整个服务可以使其在无需引入lamp-public的情况下使服务运行起来？

# 报错截图
下面两张为实际报错截图
![initInfo2](https://user-images.githubusercontent.com/36530450/189840195-c99874df-6c0d-4a2a-867c-61f4c3c56c06.png)
![initInfo1](https://user-images.githubusercontent.com/36530450/189840288-fa1b3210-ee2f-438f-81cc-87271c10d7b7.png)

下面两张为配置截图，以表明该服务可正常被编译通过，nacos配置项正常
![initInfo3](https://user-images.githubusercontent.com/36530450/189840713-a27642fb-1407-43ad-b73d-abd7a327b284.png)
![initInfo4](https://user-images.githubusercontent.com/36530450/189840786-71bb1902-6472-48a7-8843-db11f0a91104.png)

下面一张截图为对比截图，与上面的区别是在maven工程中引入了lamp-public，可以正常运行
![initSuccessInfo1](https://user-images.githubusercontent.com/36530450/189841027-e69c2b14-9979-417f-8e26-f5b734d47318.png)

# 重现步骤
1.将lamp-util，lamp-cloud均install至本地maven仓库
2.使用generator生成一个新的服务lamp-testservice3，生成路径任意（不在原工程下，与原工程隔离，为一个完全独立的微服务）
3.将lamp-testservice3-server/pom.xml中的<filter></filter>改为filters/config-${profile.active}.properties，并在该目录下增加一个文件夹filters，存放dev与prod两份properties文件，确保编译后的nacos配置文件正确
4.修改relativePath为不指定地址，从本地仓库拿lamp-dependencies-parent
5.运行lamp-testservices3，可见报错

**Comment by zuihou** [comment]
![image](https://user-images.githubusercontent.com/8500410/189842233-8ae2a3ae-dbe1-4291-af1c-a4c670ba0365.png)

想要项目不引 lamp-database-mode ，就将这里的代码 复制到各个服务去。

**Comment by pinkcao** [comment]
好的，我尝试一下

**Comment by pinkcao** [comment]
![initFailInfo1](https://user-images.githubusercontent.com/36530450/189847813-d45e1221-0c33-4eda-9013-a2bad61b4188.png)

我将@MapperScan(basePackages = {BUSINESS_PACKAGE, UTIL_PACKAGE}, annotationClass = Repository.class)
复制到了该server对应的config目录下的*MybatisConfiguration中，但与之前报相同的错，也尝试过加在ServerApplication上，均报一样的错误，希望能知道应该具体复制到哪里？还是说整个文件都复制到config目录下？（这个也尝试过，并未成功）

**Comment by zuihou** [comment]
复制过去还报错就不清楚你改到哪里了，报错就是这个注解的问题

**Comment by pinkcao** [comment]
1.将@MapperScan(basePackages = {BUSINESS_PACKAGE, UTIL_PACKAGE}, annotationClass = Repository.class)
加在Testservice4MybatisConfiguration上，报错如图
![mybatisconfiguration](https://user-images.githubusercontent.com/36530450/190087460-49b210e7-3a9a-4e6d-ae73-8651e163f45b.png)


2.将@MapperScan(basePackages = {BUSINESS_PACKAGE, UTIL_PACKAGE}, annotationClass = Repository.class)
加在Testservice4ServerApplication上，报错如图
![serverapplication](https://user-images.githubusercontent.com/36530450/190087621-931528a0-6050-4f8f-b2a4-c319830348a5.png)

这个@MapperScan注解应该放在哪里，希望能指点一下，确实是遇到了这个困难

其他的一些我自己的尝试就不截图了0.0

**Comment by zuihou** [comment]
加在什么地方都行，不信你在我原生项目上将 @MapperScan 加在不同位置试试，都是没问题的。

**Comment by zuihou** [comment]
主要不知道你改了啥，这个报错就是mybatis没读取到xml配置导致的， 加 @MapperScan 注解就是为了让mybatis能扫描到指定的包路径，并集合xml生成Mapper接口的代理实现类
