### ISSUE TITLE
修改lamp-util-pro和lamp-cloud-pro-datasource-column的关键字lamp和包路径为别的名称

### ISSUE THREAD

**Issue by shawnxiang0511** [zuihou/lamp-cloud#189]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.11.0 lamp-cloud-pro-datasource-column
MySQL(必填)：  8.0.30
Nacos(必填)：2.0.3

# 问题描述：
1、如何将工程lamp-util-pro中中关键字lamp，统一改成别的名称abc，如何统一修改top.tangyh.basic包路径名称为com.abc.basic
2、如何将工程lamp-cloud-pro-datasource-column关键字，统一修改成别的名称abc，如何统一修改top.tangyh.lamp包路径名称为com.abc.cloud

# 报错截图
1、如何将工程lamp-util-pro中中关键字lamp，统一改成别的名称abc，如何统一修改top.tangyh.basic包路径名称为com.abc.basic
2、如何将工程lamp-cloud-pro-datasource-column关键字，统一修改成别的名称abc，如何统一修改top.tangyh.lamp包路径名称为com.abc.cloud

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by pinkcao** [comment]
4.x文档/000必备资源/05批量替换项目脚本 不知道能不能帮助到你

**Comment by zuihou** [comment]
文档仓库，001必备资源 有脚本

**Comment by shawnxiang0511** [comment]
> 4.x文档/000必备资源/05批量替换项目脚本 不知道能不能帮助到你

好的，非常感谢



> 文档仓库，必备资源 有脚本

好的，非常感谢
