### ISSUE TITLE
Knife4j文档请求异常

### ISSUE THREAD

**Issue by shawnxiang0511** [zuihou/lamp-cloud#196]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.11.0 lamp-cloud-pro-datasource-column
MySQL(必填)： 5.7.9
Nacos(必填)：2.0.3

# 问题描述：
Knife4j文档请求异常

# 报错截图
Knife4j文档请求异常

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
问题描述清楚， https://github.com/zuihou/lamp-cloud/issues/175
