### ISSUE TITLE
前后端部署到腾讯云服务器 前后端访问路径不一致

### ISSUE THREAD

**Issue by leezhang19** [zuihou/lamp-cloud#197]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：lamp-boot  3.7.0 lamp-web:3.7.0
MySQL(必填)： 5.7.9
Nacos(必填)：无

# 问题描述：
在本地运行时 一切正常 但是前后端都部署到服务器 前端验证码不出  看了一下前端访问路径和后端访问路径不一样  

# 报错截图
前端访问路径
![image](https://user-images.githubusercontent.com/57745942/192678854-cb0652cd-35b7-45b2-a208-d47357deec52.png)

后端访问路径
![image](https://user-images.githubusercontent.com/57745942/192679079-69efb438-14b0-492f-9d18-692dde85c29a.png)

# 重现步骤
1. 访问了什么接口？
(http://43.143.166.9:8760/api/oauth/anno/captcha?key=E94B5023838AA5F6737CC13E1664334341695&ts=1664334341711)
3. 传递什么参数？
4. 后端控制台报了什么错？
![image](https://user-images.githubusercontent.com/57745942/192679212-de7b827e-f3a3-41e9-8549-9c6c872e811d.png)
6. 前端控制台报了什么错？
验证码不出
![image](https://user-images.githubusercontent.com/57745942/192679449-10c301fa-3ea0-43a5-bb0d-2a5941d8de38.png

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
在nginx 配置`location /api/xxx`  和 `location /lamp-web` 的代理， 然后浏览器访问和请求的ip和端口需要一致
 
https://www.kancloud.cn/zuihou/zuihou-admin-cloud/2405129
