### ISSUE TITLE
schema 模式下的多租户. seata 分布式事务问题. 回滚如何找到schema的.

### ISSUE THREAD

**Issue by siaron** [zuihou/lamp-cloud#226]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
1. schema 模式下的多租户
2. seata 分布式事务问题. 回滚如何找到schema的

**Comment by zuihou** [comment]
schema 模式就是在原始SQL基础上，拼接schema，如：  select *  from user 替换为 select * from db1.user

分布式事务如何支持schema模式，应该去seata官方提问。

我测试过seata 1.4.2， 是支持insert update select 等简单sql 的
