### ISSUE TITLE
Unrecognised tag: 'snapshotPolicy' (position: START_TAG seen ...</layout>  \n\t\t\t<snapshotPolicy>... @233:20)  @ E:\apache-maven-3.6.1\conf\settings.xml, line 233, column 20

### ISSUE THREAD

**Issue by arraycto** [zuihou/lamp-cloud#34]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：截止2020年10月21日最新版
MySQL(必填)： 5.7.9
Nacos(必填)：1.2.
mave：apache-maven-3.6.1

# 问题描述：
编译commons项目无法通过

# 报错截图
![zui](https://user-images.githubusercontent.com/37463247/96734179-d879c280-13ec-11eb-8cff-4bbab148b36d.jpg)

```
Some problems were encountered while building the effective settings
Unrecognised tag: 'snapshotPolicy' (position: START_TAG seen ...</layout>  \n\t\t\t<snapshotPolicy>... @233:20)  @ E:\apache-maven-3.6.1\conf\settings.xml, line 233, column 20
Unrecognised tag: 'snapshotPolicy' (position: START_TAG seen ...</layout>  \n\t\t\t<snapshotPolicy>... @233:20)  @ E:\\apache-maven-3.6.1\conf\settings.xml, line 233, column 20
```

# 重现步骤

下载commons项目编译

**Comment by tyunh** [comment]
![Uploading image.png…]()

加QQ群, 下载群文件里面的maven setting.xml , 然后: 
1. 将 zuihou-commons/zuihou-dependencies/pom.xml 导入IDEA
2. 编译zuihou-dependencies/pom.xml：mvn clean install -Dmaven.javadoc.skip=true -Dgpg.skip=true -Dmaven.source.skip=true -DskipTests=true
3. 将 zuihou-commons/pom.xml 导入IDEA
4. 编译zuihou-commons/pom.xml： mvn clean install -Dmaven.javadoc.skip=true -Dgpg.skip=true -Dmaven.source.skip=true -DskipTests=true

**Comment by arraycto** [comment]
已经添加，衍生处理的问题，zuihou-core:jar is missing. @ line 18, column 21一直找不到版本，原版程序，不应该啊。麻烦提供一下排查思路。对了安装您上面所说的进行操作的仍旧这个问题。依旧编译commons项目的时候出问题

**Comment by arraycto** [comment]
请问大佬为何直接用aliyun的仓库不可以，不能满足，是楼主用的jar较特殊吗？新手哈，感谢
