### ISSUE TITLE
租户创建时接口404

### ISSUE THREAD

**Issue by pruod** [zuihou/lamp-cloud#43]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：lamp
MySQL(必填)： 5.7.9
Nacos(必填)：1.1.4

# 问题描述：
![image](https://user-images.githubusercontent.com/30286418/101451361-faacad00-3966-11eb-897d-815599fbb4cd.png)

# 报错截图

# 重现步骤
1. http://localhost:8080/api/tenant/datasourceConfig
2. {"id":"","name":"0001-基础服务","username":"root","password":"123456","driverClassName":"com.mysql.cj.jdbc.Driver","url":"jdbc:mysql://127.0.0.1:3306/lamp_base_0001?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true"}
3. 后端控制台报了 not exec!!! url=http://127.0.0.1:8760/datasourceConfig
4. 前端控制台报了404

**Comment by zuihou** [comment]
开源版请忽略这个报错,没影响
