### ISSUE TITLE
如何实现各个模块连接不同的数据库

### ISSUE THREAD

**Issue by xiaozhang-dev** [zuihou/lamp-cloud#46]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：

# 报错截图

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
看你用什么模式
