### ISSUE TITLE
服务之间调用的疑问

### ISSUE THREAD

**Issue by wangyiidii** [zuihou/lamp-cloud#63]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
![](https://tu.yaohuo.me/imgs/2020/12/c131be69122578aa.png)

问题描述如上，不吝指教

**Comment by zuihou** [comment]
1. 描述对的
2. 认证服务、权限服务、租户服务本就是依赖比较大的，最初的版本甚至都是3个服务合并在一起的
3. 拆分后，没有走远程调用是为了防止分布式事务和出于性能考虑

**Comment by shangguanbaojun** [comment]
> 1. 描述对的
> 2. 认证服务、权限服务、租户服务本就是依赖比较大的，最初的版本甚至都是3个服务合并在一起的
> 3. 拆分后，没有走远程调用是为了防止分布式事务和出于性能考虑

### system服务下的facade中，cloud-impl中的api下的方法，在其他服务中怎么调用。
![image](https://github.com/user-attachments/assets/5052cccd-6de5-4f15-90a8-549d8261d51f)

**Comment by zuihou** [comment]
5.x以后， lamp-xxx-api 层的接口用于提供给其他服务调用，
lamp-xxx-cloud-impl 和 lamp-xxx-boot-impl 则是 lamp-xxx-api 层的实现。


比如： 
base服务需要调用 system服务的接口，就在base服务的lamp-base-biz层加入 lamp-system-api 层的依赖，调用lamp-sysetm-api 中的接口。
- 单体版：并在 lamp-boot-server 层加入 lamp-system-boot-impl 依赖。
- 微服务版：并在 lamp-base-server 层加入 lamp-system-cloud-impl 依赖。
cloud-impl和boot-impl层，只用于实现system-api层的接口。  


你截图中的接口，只是cloud-impl的内部接口，不能给其他服务调用的。  其他服务想要调用，直接使用 lamp-system-api 的接口

**Comment by shangguanbaojun** [comment]
> 5.x以后， lamp-xxx-api 层的接口用于提供给其他服务调用， lamp-xxx-cloud-impl 和 lamp-xxx-boot-impl 则是 lamp-xxx-api 层的实现。
> 
> 比如： base服务需要调用 system服务的接口，就在base服务的lamp-base-biz层加入 lamp-system-api 层的依赖，调用lamp-sysetm-api 中的接口。
> 
> * 单体版：并在 lamp-boot-server 层加入 lamp-system-boot-impl 依赖。
> * 微服务版：并在 lamp-base-server 层加入 lamp-system-cloud-impl 依赖。
>   cloud-impl和boot-impl层，只用于实现system-api层的接口。
> 
> 你截图中的接口，只是cloud-impl的内部接口，不能给其他服务调用的。 其他服务想要调用，直接使用 lamp-system-api 的接口

按照这个步骤操作，新建的服务biz加入了lamp-system-api依赖，server 层也加入 lamp-system-cloud-impl 依赖。
在新建服务的serviceImpl中引入system的Facade，导致新建服务无法启动
![image](https://github.com/user-attachments/assets/d4429a97-86c3-41ee-ac9e-2955ab466217)

下面是启动信息：
![image](https://github.com/user-attachments/assets/4d4f02f1-2600-4306-aaca-ffe6714884c1)

**Comment by zuihou** [comment]
BeDeviceFacede 的实现类呢？

**Comment by shangguanbaojun** [comment]
> BeDeviceFacede 的实现类呢？

### 下面是service服务中BeDeviceFacede 实现类的代码
![image](https://github.com/user-attachments/assets/1c496746-585d-4808-97f3-2b572460ca00)

### 下面是service服务中BzDeviceService实现类中的方法
![image](https://github.com/user-attachments/assets/51808443-b8a1-4b18-b734-2868f6b82b40)

### service服务链接的是lamp_cloud库，device服务链接的是lamp_cloud_device库。但是94行报错，报错信息如下：
![image](https://github.com/user-attachments/assets/113c8da4-1f62-498b-9f2c-2d03de116339)

奇怪的是表是service服务中的表，库怎么是device服务的库。这是什么原因？

**Comment by zuihou** [comment]
你自己说了：service服务链接的是lamp_cloud库，device服务链接的是lamp_cloud_device库。

所以，执行的代码在service服务，就链接的是lamp_cloud库，代码位于device服务，就链接的是lamp_cloud_device库。
没毛病

**Comment by shangguanbaojun** [comment]
目的是数据需要在device服务的lamp_column_device库中保存一份，同时把数据也存到service服务中的lamp_column库中一份。现在的代码逻辑是，device服务引入了lamp-system-api依赖。然后在device服务中的service实现类中引入了service服务中的BzDeviceFacede，然后BzDeviceFacedeImpl中调用了service服务中BzDeviceService中的保存方法。 现在的情况是device服务lamp_column_device中的device表中存储成功了，service服务的lamp_column库中的bz_device中没有数据，保存失败，但是报错信息中的错误是Table 'lamp_column_device.bz_device' doesn't exist。在这个信息中，lamp_column_device是device服务的库，但是bz_device表是service中的表。是代码顺序需要调整吗？

**Comment by zuihou** [comment]
然后BzDeviceFacedeImpl中调用了service服务中BzDeviceService中的保存方法。 

微服务项目，不应该在BzDeviceFacedeImpl中调用了service服务中BzDeviceService中的保存方法，
 应该在BzDeviceFacedeImpl中调用了service服务的接口，通过openfeign方式调用，而不能以 本地类调用的方式调用。




原因：
然后BzDeviceFacedeImpl中调用了service服务中BzDeviceService中的保存方法。  实际上执行的就是操作的就是 device服务的库

**Comment by shangguanbaojun** [comment]
项目中有openfeign调用的例子嘛？

**Comment by zuihou** [comment]
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/601fb2a0-27bb-4efd-a28f-53845d5fe6a3">

**Comment by shangguanbaojun** [comment]
![image](https://github.com/user-attachments/assets/8e1c7dd3-7589-4ee9-9dd7-e2ca1357165c)

API中的方法怎么调用，调用地址嘛？

**Comment by zuihou** [comment]
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/ef9bd1c1-a787-433d-8683-791ba54f9b24">


openfeign 不会用的话， 建议使用单体版本，或者先通过百度等渠道学习后再使用 微服务版本

**Comment by shangguanbaojun** [comment]
项目中有微服务之间调用的相关例子嘛？
