### ISSUE TITLE
schema模式下无法使用mybatis的嵌套查询

### ISSUE THREAD

**Issue by xxmiao1006** [zuihou/lamp-cloud#66]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 8
Nacos(必填)：

# 问题描述：
schema模式下无法使用mybatis的嵌套查询
schema模式下mybatis使用关联嵌套查询（2个select表名），动态添加表名的SchemaInterceptor无法给每次查询添加表名。只给第一条添加

# 报错截图
![image](https://user-images.githubusercontent.com/37374467/103083785-3d81ac80-4618-11eb-84e6-3b174cf62c97.png)
![image](https://user-images.githubusercontent.com/37374467/103083844-6b66f100-4618-11eb-95d1-0cf25b7ce268.png)

查询的两条sql
 tenant: 0000 userId: 3 
 Consume Time：46 ms 2020-12-24 18:45:23 
 url: jdbc:mysql://106.**.**.***:3306/zuihou_defaults?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true 
 Execute SQL：SELECT DISTINCT a.biz_id AS biz_id, a.biz_type AS biz_type FROM **zuihou_base_0000.f_attachment** a WHERE 1 = 1 AND a.biz_id IN ('36889289422029825') 

 tenant: 0000 userId: 3 
 Consume Time：47 ms 2020-12-24 18:45:23 
 url: jdbc:mysql://106.**.**.***:3306/zuihou_defaults?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true 
 Execute SQL：SELECT id, create_time, create_user, update_time, update_user, biz_id, biz_type, data_type, submitted_file_name, group_, path, relative_path, url, file_md5, context_type, filename, ext, size, org_id, icon, create_month, create_week, create_day FROM **f_attachment** a where a.biz_id = '36889289422029825' and a.biz_type = '2' order by a.create_time desc 

# 重现步骤
1. 访问了什么接口？
在schema模式下启动项目，调用了AttachmentController的findAttachment方法，这个方法实现是一个mybatis的关联嵌套查询
2. 传递什么参数？
3. 后端控制台报了什么错？
返回结果的list为空，无法查询到
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
将SchemaInterceptor 代码按如下修改试试（已经自测一遍），  系统每个功能都测试下，有问题及时反馈。
```

import cn.hutool.core.util.StrUtil;
import com.baomidou.mybatisplus.core.plugins.InterceptorIgnoreHelper;
import com.baomidou.mybatisplus.core.toolkit.PluginUtils;
import com.baomidou.mybatisplus.extension.plugins.inner.InnerInterceptor;
import com.tangyh.basic.context.ContextUtil;
import com.tangyh.basic.database.parsers.ReplaceSql;
import lombok.extern.slf4j.Slf4j;
import org.apache.ibatis.executor.Executor;
import org.apache.ibatis.executor.statement.StatementHandler;
import org.apache.ibatis.mapping.BoundSql;
import org.apache.ibatis.mapping.MappedStatement;
import org.apache.ibatis.mapping.SqlCommandType;
import org.apache.ibatis.session.ResultHandler;
import org.apache.ibatis.session.RowBounds;

import java.sql.Connection;
import java.sql.SQLException;

public class SchemaInterceptor implements InnerInterceptor {

    private final String tenantDatabasePrefix;

    public SchemaInterceptor(String tenantDatabasePrefix) {
        this.tenantDatabasePrefix = tenantDatabasePrefix;
    }

    protected String changeTable(String sql) {
        // 想要 执行sql时， 不切换到 lamp_base_{TENANT} 库, 请直接返回null
        String tenantCode = ContextUtil.getTenant();
        if (StrUtil.isEmpty(tenantCode)) {
            return sql;
        }

        String schemaName = StrUtil.format("{}_{}", tenantDatabasePrefix, tenantCode);
        // 想要 执行sql时， 切换到 切换到自己指定的库， 直接修改 setSchemaName
        return ReplaceSql.replaceSql(schemaName, sql);
    }

    @Override
    public void beforeQuery(Executor executor, MappedStatement ms, Object parameter, RowBounds rowBounds, ResultHandler resultHandler, BoundSql boundSql) throws SQLException {
        // 统一交给 beforePrepare 处理,防止某些sql解析不到，又被beforePrepare重复处理
    }


    @Override
    public void beforePrepare(StatementHandler sh, Connection connection, Integer transactionTimeout) {
        PluginUtils.MPStatementHandler mpSh = PluginUtils.mpStatementHandler(sh);
        MappedStatement ms = mpSh.mappedStatement();
        SqlCommandType sct = ms.getSqlCommandType();
        if (sct == SqlCommandType.INSERT || sct == SqlCommandType.UPDATE || sct == SqlCommandType.DELETE || sct == SqlCommandType.SELECT) {
            if (InterceptorIgnoreHelper.willIgnoreDynamicTableName(ms.getId())) {
                return;
            }
            PluginUtils.MPBoundSql mpBs = mpSh.mPBoundSql();
            log.debug("未替换前的sql: {}", mpBs.sql());
            mpBs.sql(this.changeTable(mpBs.sql()));
        }
    }
}
```

**Comment by xxmiao1006** [comment]
👍
