### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by zhonglh** [zuihou/lamp-cloud#70]
zuihou : 你好
    从 去年开始一直关注您的项目， 从中学习到了很多， 非常感谢。查看源码的时候发现有几点我感觉不方便的地方:
1. 验证权限的时候， 每验证一个权限都要通过api 查询另外一个服务，这样一来时间上估计会消耗比较多
2.兼容boot和cloud项目， 在injection 项目， 是否可以在实体类里把api 和 service 都配置上， 这样通过springutil.getBean("xxxserviceimpl")来获取 ， 没有bean 再通过 springutil.getBean("xxxapi")  来获取，
这样能满足两个项目，而且还不需要配置.  在security 项目上也是如此， 把api 和  service 方式都配置上， 然后通过springutil的getbean 来判断， 这样可以兼容两种项目方式，而且也不需要用户来配置FEIGN/SERVICRE,保存日志也是如此兼容这两个项目， 最好的效果是一个项目， 有一个配置项上配置是boot还是cloud , boot的启动项目只是依赖其它所有的controller module 
3. 菜单  权限这两个表的数据都是一模一样的， 是否可以提到zuihou-defaults库里 
4. 通过feign 方式调用的 controller ， 在controller 是否可以不检验权限。

**Comment by zhonglh** [comment]
还有一点就是对于枚举支持两种传参  sex=xxx , sex:{key:xxx} , 那么 InjectionField 是否也可以支持

**Comment by zuihou** [comment]
1. 为了兼容boot 和 cloud 的权限一致，没有采用网关验证的方式， 但又引入你说的这个问题， 考虑过在api调用前加缓存， 但又会增加耦合度和复杂性， 故通过api远程调用，在接口提供方实现缓存（多了api调用开销，少了复杂性和耦合性）
2. 感谢建议，后面考虑下按此思路调整。
3. 说的是c_auth_menu(c_menu)和c_auth_resource(c_resource)表吗？ 这2个表有一些重叠字段，但也有一些区别，合并或者拆分都各自有理。  但放在defaults库则不可取， 因为是为租户提供的功能， defaults库里面的都是全局表。
4. 可以增加此功能
5. 应该可以增加此功能（需要调试）

**Comment by zuihou** [comment]
> 还有一点就是对于枚举支持两种传参 sex=xxx , sex:{key:xxx} , 那么 InjectionField 是否也可以支持

已支持

**Comment by zuihou** [comment]
> zuihou : 你好
> 从 去年开始一直关注您的项目， 从中学习到了很多， 非常感谢。查看源码的时候发现有几点我感觉不方便的地方:
> 
> 1. 验证权限的时候， 每验证一个权限都要通过api 查询另外一个服务，这样一来时间上估计会消耗比较多
>    2.兼容boot和cloud项目， 在injection 项目， 是否可以在实体类里把api 和 service 都配置上， 这样通过springutil.getBean("xxxserviceimpl")来获取 ， 没有bean 再通过 springutil.getBean("xxxapi")  来获取，
>    这样能满足两个项目，而且还不需要配置.  在security 项目上也是如此， 把api 和  service 方式都配置上， 然后通过springutil的getbean 来判断， 这样可以兼容两种项目方式，而且也不需要用户来配置FEIGN/SERVICRE,保存日志也是如此兼容这两个项目， 最好的效果是一个项目， 有一个配置项上配置是boot还是cloud , boot的启动项目只是依赖其它所有的controller module
> 2. 菜单  权限这两个表的数据都是一模一样的， 是否可以提到zuihou-defaults库里
> 3. 通过feign 方式调用的 controller ， 在controller 是否可以不检验权限。

1. 正在研究
2. 拒绝 
3. 已支持

**Comment by liangfutang** [comment]
大概看了下，没有具体去验证哈，
gateway模块的TraceFilter 改成用WebFilter(且排序靠前点)是不是会好点，如果用GlobalFilter会导致你前面的webfilter实现类如TokenContextFilter 等代码日志拿不到traceID
