### ISSUE TITLE
用Jmter对接口进行压测，发现并发数不高且没有超时的情况下网关直接熔断

### ISSUE THREAD

**Issue by xxmiao1006** [zuihou/lamp-cloud#73]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：用jmeter对接口进行压测，通过三种方式 1.直接调用服务 2.网关（gateway）->服务 3.nginx->网关->服务，发现第一种方式接口的并发线程数比较高，但是通过第二种方式时并发线程数达到20就不行了，网关直接fallback，返回code=-2，但是明显服务是能处理过来的，并没有接口超时。

# 报错截图
在gateway-server的FallbackController里面将熔断的原因打印出来
![image](https://user-images.githubusercontent.com/37374467/105454353-b11ce500-5cbc-11eb-81ec-c85595df2812.png)

最后发现控制台打印的是
could not acquire a semaphore for execution
大概原因是说Hystrix请求不到信号量了。后来common.yml里将hystrix的信号量配置改了以下，并发数就上去了。
https://juejin.cn/post/6844903762331435022
![image](https://user-images.githubusercontent.com/37374467/105454615-225c9800-5cbd-11eb-86af-dbc4fc948391.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by xxmiao1006** [comment]
不知道是否是我漏掉了配置的原因？

**Comment by zuihou** [comment]
正解。
