### ISSUE TITLE
多数据源

### ISSUE THREAD

**Issue by Bennett-Q** [zuihou/lamp-cloud#74]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
schema模式下 怎么添加多数据源呢，需要用到clickhouse

**Comment by zuihou** [comment]
暂时未考虑过如何同时集成多个数据库。

**Comment by Bennett-Q** [comment]
那如果我想在执行某个mapper方法sql的过程中，切到其他数据源应该在哪修改

**Comment by zuihou** [comment]
参考 https://gitee.com/zuihou111/lamp-boot/issues/I2SDYL#note_4181256

**Comment by Bennett-Q** [comment]
好的~谢谢

**Comment by Bennett-Q** [comment]
public SlaveDatabaseAutoConfiguration(MybatisPlusSlaveProperties properties,
                                          DatabaseProperties databaseProperties,
                                          ObjectProvider<Interceptor[]> interceptorsProvider,
                                          ObjectProvider<TypeHandler[]> typeHandlersProvider,
                                          ObjectProvider<LanguageDriver[]> languageDriversProvider,
                                          ResourceLoader resourceLoader,
                                          ObjectProvider<DatabaseIdProvider> databaseIdProvider,
                                          ObjectProvider<List<ConfigurationCustomizer>> configurationCustomizersProvider,
                                          ObjectProvider<List<MybatisPlusPropertiesCustomizer>> mybatisPlusPropertiesCustomizerProvider,
                                          ApplicationContext applicationContext) {
        super(properties, databaseProperties, interceptorsProvider, typeHandlersProvider,
                languageDriversProvider, resourceLoader, databaseIdProvider,
                configurationCustomizersProvider, mybatisPlusPropertiesCustomizerProvider, applicationContext);
    }

自建的SlaveDatabaseAutoConfiguration类，这是第10步改了第一个构造参数之后，与父类不一样，直接报错，走不下去了~楼主那边有成功案例吗
