### ISSUE TITLE
请教一下 grayversion: zuihou 是什么意思，与哪里有关联

### ISSUE THREAD

**Issue by 18285160741** [zuihou/lamp-cloud#78]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
求指点：spring.cloud.nacos.discovery.metadata.grayversion: zuihou 是什么意思，与哪里有关联。
是否可以修改？谢谢

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
灰度发布时使用，开源版忽略该配置，直接删除都行。

会员版 在服务A的3个节点配置这个值后，想要实现灰度发布，第4个节点只要配置不同的参数，
在请求头中传递相同的参数，可以实现请求始终达到节点4的效果
