### ISSUE TITLE
求指点：同一台机器，IDEA能正常运行，打jar包无法运行

### ISSUE THREAD

**Issue by 18285160741** [zuihou/lamp-cloud#79]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
麻烦大佬指点迷津，谢谢

IDEA导入项目可以正常运行

![image](https://user-images.githubusercontent.com/37412616/108961845-e13c1700-76b2-11eb-8caf-712bad497e99.png)

打jar包 无法运行，一直提示没有配置数据源
![image](https://user-images.githubusercontent.com/37412616/108962021-1d6f7780-76b3-11eb-8f27-7388ca425fe8.png)
![image](https://user-images.githubusercontent.com/37412616/108962084-34ae6500-76b3-11eb-9bb3-29b0eb61883d.png)
![image](https://user-images.githubusercontent.com/37412616/108962178-590a4180-76b3-11eb-8110-1a9f954c3a20.png)

**Comment by 18285160741** [comment]
目前我感觉应该是文件编码问题，同样的jar包我放到Linux系统能跑起来。
windows上我参考 #52 在启动是传递编码utf-8还是不能解决。
![image](https://user-images.githubusercontent.com/37412616/108968277-8b1fa180-76bb-11eb-83df-ff3aa16d114f.png)

**Comment by zuihou** [comment]
1， 设置utf8
或者
2,  去除配置文件中的中文

**Comment by 18285160741** [comment]
参数 utf-8 改为utf8居然可以起来了。感谢感谢
