### ISSUE TITLE
cloud的NONE模式，读不到nacos

### ISSUE THREAD

**Issue by xswby** [zuihou/lamp-cloud#95]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：3.2.4
MySQL(必填)： 5.7.9
Nacos(必填)：alone
 

# 问题描述：
采用NONE模式，数据库也到导入defaults的base_0000到 lamp_none

# 报错截图
[main:32704] [com.alibaba.nacos.common.remote.client.printIfErrorEnabled:99] Send request fail, request=ConfigQueryRequest{headers={charset=UTF-8, exConfigInfo=true, Client-AppName=unknown, Client-RequestTS=1626276413505, Client-RequestToken=f9df43acdebe168a98e4bbc526ac3895, accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYyNjI5NDM5Mn0.0ZnbCXrr1L4UvHO-I43BxdvJu6oCxN7gEB87jb-wQPg, Timestamp=1626276413507, notify=false}, requestId='null'}, retryTimes=0,errorMessage=Client not connected,current status:STARTING
[lamp-authority-server:0000::] 2021-07-14 23:26:53.775:[ERROR] [11097] [] [main:32806] [com.alibaba.nacos.common.remote.client.printIfErrorEnabled:99] Send request fail, request=ConfigQueryRequest{headers={charset=UTF-8, exConfigInfo=true, Client-AppName=unknown, Client-RequestTS=1626276413505, Client-RequestToken=f9df43acdebe168a98e4bbc526ac3895, accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYyNjI5NDM5Mn0.0ZnbCXrr1L4UvHO-I43BxdvJu6oCxN7gEB87jb-wQPg, Timestamp=1626276413507, notify=false}, requestId='null'}, retryTimes=1,errorMessage=Client not connected,current status:STARTING
[lamp-authority-server:0000::] 2021-07-14 23:26:53.876:[ERROR] [11097] [] [main:32907] [com.alibaba.nacos.common.remote.client.printIfErrorEnabled:99] Send request fail, request=ConfigQueryRequest{headers={charset=UTF-8, exConfigInfo=true, Client-AppName=unknown, Client-RequestTS=1626276413505, Client-RequestToken=f9df43acdebe168a98e4bbc526ac3895, accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYyNjI5NDM5Mn0.0ZnbCXrr1L4UvHO-I43BxdvJu6oCxN7gEB87jb-wQPg, Timestamp=1626276413507, notify=false}, requestId='null'}, retryTimes=2,errorMessage=Client not connected,current status:STARTING
[lamp-authority-server:0000::] 2021-07-14 23:26:53.883:[ WARN] [11097] [] [main:32914] [c.a.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData:87] Ignore the empty nacos configuration and get it based on dataId[common.yml] & group[DEFAULT_GROUP]
[lamp-authority-server:0000::] 2021-07-14 23:26:53.990:[ERROR] [11097] [] [main:33021] [com.alibaba.nacos.common.remote.client.printIfErrorEnabled:99] Send request fail, request=ConfigQueryRequest{headers={charset=UTF-8, exConfigInfo=true, Client-AppName=unknown, Client-RequestTS=1626276413887, Client-RequestToken=8342d3cd1c01204a4f6e9346745006d8, accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYyNjI5NDM5Mn0.0ZnbCXrr1L4UvHO-I43BxdvJu6oCxN7gEB87jb-wQPg, Timestamp=162627

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下

**Comment by xswby** [comment]
nacos.ip=47.111.189.105
nacos.port=8848
# 独立命名空间避免跟别的项目冲突
nacos.namespace=57d41ddd-c089-449f-8921-bd0e8af14ddc
nacos.username=nacos
nacos.password=nacos

**Comment by xswby** [comment]
nacos.ip=47.111.189.105
nacos.port=8848
nacos.namespace=57d41ddd-c089-449f-8921-bd0e8af14ddc
nacos.username=nacos
nacos.password=nacos

**Comment by xswby** [comment]
nacos的配置：
nacos.ip=47.111.189.105
nacos.port=8848
nacos.namespace=57d41ddd-c089-449f-8921-bd0e8af14ddc
nacos.username=nacos
nacos.password=nacos

**Comment by xswby** [comment]
nacos版本：1.3.0

**Comment by zuihou** [comment]
nacos-sever 和 nacos-client 的版本号要保持一致  
3.2.4 版本，nacos-client 用的是 2.0.0 版本， 所以nacos server 也需要2.0.0 版本

![image](https://user-images.githubusercontent.com/8500410/125718147-c2ea051d-32d9-4ce3-8eff-5cf59775e6cf.png)
